apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: payshield-config
    behavior: merge
    literals:
      - LOG_LEVEL=WARNING
      - CORS_ORIGINS=https://dashboard.payshield.io

patchesStrategicMerge:
  - patch-ingress.yaml

images:
  - name: payshield/api
    newTag: prod-{BUILD_TAG}
  - name: payshield/celery-worker
    newTag: prod-{BUILD_TAG}

namespace: payshield-prod
