/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        secondary: "#9ed2ba",
        outline: "#998f81",
        "on-secondary-container": "#90c3ac",
        "surface-tint": "#e3c282",
        "surface-dim": "#16130f",
        "on-primary-fixed": "#261a00",
        tertiary: "#bac7f4",
        "surface-variant": "#38342f",
        "on-primary-container": "#533d09",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#1e4f3d",
        "surface-container-low": "#1e1b17",
        "primary-fixed": "#ffdea0",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#334064",
        "outline-variant": "#4d463a",
        "tertiary-fixed-dim": "#b8c5f2",
        surface: "#16130f",
        "on-tertiary": "#222f53",
        "primary-container": "#c8a96b",
        "on-background": "#e9e1da",
        "on-secondary-fixed": "#002116",
        "inverse-primary": "#735b25",
        "secondary-fixed-dim": "#9ed2ba",
        "inverse-on-surface": "#33302b",
        "surface-container-high": "#2d2925",
        background: "#16130f",
        error: "#ffb4ab",
        "on-tertiary-fixed-variant": "#39466b",
        "error-container": "#93000a",
        "on-secondary": "#003828",
        "surface-container": "#221f1b",
        "primary-fixed-dim": "#e3c282",
        primary: "#e5c484",
        "on-primary": "#402d00",
        "on-surface-variant": "#d0c5b5",
        "tertiary-fixed": "#dae1ff",
        "on-surface": "#e9e1da",
        "surface-bright": "#3c3933",
        "on-primary-fixed-variant": "#5a430f",
        "secondary-container": "#205240",
        "secondary-fixed": "#baeed5",
        "surface-container-lowest": "#100e0a",
        "tertiary-container": "#9facd7",
        "surface-container-highest": "#38342f",
        "inverse-surface": "#e9e1da",
        "on-tertiary-fixed": "#0b1a3d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-padding-mobile": "20px",
        "section-gap": "120px",
        "container-padding-desktop": "64px",
        unit: "4px",
      },
      fontFamily: {
        "body-md": ["Geist", "ui-sans-serif", "system-ui"],
        "display-lg": ["Instrument Serif", "serif"],
        "display-lg-mobile": ["Instrument Serif", "serif"],
        "headline-md": ["Instrument Serif", "serif"],
        "body-lg": ["Geist", "ui-sans-serif", "system-ui"],
        "title-lg": ["Geist", "ui-sans-serif", "system-ui"],
        "mono-data": ["Geist", "ui-monospace", "monospace"],
        "label-caps": ["Geist", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "500" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};