graph_schema:
  node_types:
    - user
    - merchant
    - device
    - transaction
  edge_types:
    - [user, performed, transaction]
    - [transaction, to, merchant]
    - [user, used, device]
    - [user, transferred_to, user]
    - [device, shared_by, user]
  node_feature_dims:
    user: 5
    merchant: 19
    device: 4
    transaction: 4
  num_classes: 2
