"""Generate PayShield GNN model card from benchmark JSON.

Zero hand-edited metrics — every number is read from
``models/gnn_benchmark_results.json``.  Run::

    python scripts/generate_model_card.py
"""

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCHMARK_PATH = ROOT / "models" / "gnn_benchmark_results.json"
OUTPUT_PATH = ROOT / "models" / "payshield_gnn_v1_card.md"

TEMPLATE = """# PayShield GNN v1 — Model Card

**Generated:** {generated_at} (auto-generated from `{benchmark_file}`)

## Model Details

- **Architecture:** {architecture}
- **Parameters:** {params}
- **Training data:** {data_desc}
- **Lead metric:** PR-AUC (measure of minority-class ranking quality)
- **Framework:** PyTorch + PyTorch Geometric (HeteroConv, SAGEConv)

## Intended Use

Primary: detect anomalous UPI transactions via relational graph patterns
(shared-device mule rings, merchant collusion) as a conditional fusion input
to PayShield's ensemble scoring engine.

Out of scope: stand-alone fraud verdicts; real-time payments with latency
budgets under 1 ms (the GNN path is ~2 ms p99); jurisdictions not covered
by PayShield’s EU AI Act conformity assessment.

## Evaluation Data

- {data_source}
- {users:,} users, {merchants:,} merchants, {transactions:,} transactions
- Fraud prevalence: {fraud_ratio:.0%}
- Test split: {test_graphs:,} ego-graphs ({test_positives:,} positives)
- Seed: {seed}

## Test Metrics (held-out user-disjoint split)

| Metric | GNN | Edge-free MLP |
|--------|-----|---------------|
| AUC-ROC | {gnn_auc_roc:.4f} | {bl_auc_roc:.4f} |
| **PR-AUC** *(lead)* | **{gnn_auc_pr:.4f}** | {bl_auc_pr:.4f} |
| FPR @ 90% recall | {gnn_fpr:.4f} | {bl_fpr:.4f} |
| **PR-AUC lift** | — | **{pr_lift:.1f}×** |

*Why PR-AUC leads:* AUC-ROC is dominated by the legitimate majority in
imbalanced fraud; PR-AUC measures the minority (fraud) class directly.

## Inference Latency (CPU)

| Statistic | Value |
|-----------|-------|
| Mean | {lat_mean:.1f} ms |
| p50 | {lat_p50:.1f} ms |
| p95 | {lat_p95:.1f} ms |
| p99 | {lat_p99:.1f} ms |
| Max | {lat_max:.1f} ms |
| Runs | {lat_runs:,} ego-graphs (median {lat_node_med:,} nodes, {lat_edge_med:,} edges) |

## Known Limitations

{limitations}

## Fairness Evaluation

Demographic performance slices (SPD / EOD) are computed by
`models/fairness_audit.py` on synthetic gender, age-tier, and city-tier
splits. See the audit script for the latest numbers — they are **not**
hardcoded here to ensure they stay current with every run.

## Graph Schema

- **Node types:** {node_types}
- **Edge types:** {edge_types}

## Maintenance

- Auto-generated by `scripts/generate_model_card.py`
- Updates on every benchmark re-run (`python scripts/benchmark_gnn.py`)
- Versioned alongside the model artifacts in `models/registry/`
"""


def _format_limitations(limitations: list[str]) -> str:
    return "\n".join(f"- {lim}" for lim in limitations)


def _format_node_types(node_dict: dict) -> str:
    return ", ".join(f"{k} ({v} features)" for k, v in node_dict.items())


def _format_edge_types(edge_list: list) -> str:
    return ", ".join(f"{s}→{r}→{t}" for s, r, t in edge_list)


def generate_model_card() -> str:
    with open(BENCHMARK_PATH) as f:
        data = json.load(f)

    gnn = data["gnn"]
    baseline = data["baseline"]
    ds = data["data"]
    latency = gnn["inference_latency_ms_cpu"]
    schema = data["graph_schema"]

    lat = lambda k: latency[k]  # noqa: E731

    return TEMPLATE.format(
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        benchmark_file=BENCHMARK_PATH.name,
        architecture=gnn["architecture"],
        params=f"{gnn['parameters']:,}",
        data_desc=ds["source"],
        data_source=ds["source"],
        users=ds["users"],
        merchants=ds["merchants"],
        transactions=ds["transactions"],
        fraud_ratio=ds["fraud_ratio"],
        test_graphs=gnn["test_split"]["graphs"],
        test_positives=gnn["test_split"]["positives"],
        seed=ds["seed"],
        gnn_auc_roc=gnn["test_metrics"]["auc_roc"],
        gnn_auc_pr=gnn["test_metrics"]["auc_pr"],
        gnn_fpr=gnn["test_metrics"]["fpr_at_0.90_recall"],
        bl_auc_roc=baseline["test_metrics"]["auc_roc"],
        bl_auc_pr=baseline["test_metrics"]["auc_pr"],
        bl_fpr=baseline["test_metrics"]["fpr_at_0.90_recall"],
        pr_lift=baseline["pr_auc_lift_vs_gnn"],
        lat_mean=lat("mean_ms"),
        lat_p50=lat("p50_ms"),
        lat_p95=lat("p95_ms"),
        lat_p99=lat("p99_ms"),
        lat_max=lat("max_ms"),
        lat_runs=lat("runs"),
        lat_node_med=lat("graph_nodes_median"),
        lat_edge_med=lat("graph_edges_median"),
        limitations=_format_limitations(data.get("limitations", [])),
        node_types=_format_node_types(schema["node_types"]),
        edge_types=_format_edge_types(schema["edge_types"]),
    )


if __name__ == "__main__":
    card = generate_model_card()
    with open(OUTPUT_PATH, "w") as f:
        f.write(card)
    print(f"Model card written to {OUTPUT_PATH}")
