apiVersion: v1
kind: Service
metadata:
  name: payshield-api
  labels:
    app.kubernetes.io/name: payshield
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
  selector:
    app.kubernetes.io/name: payshield
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: payshield-ws
  labels:
    app.kubernetes.io/name: payshield
    app.kubernetes.io/component: ws
spec:
  type: ClusterIP
  ports:
    - name: ws
      port: 8765
      targetPort: 8765
  selector:
    app.kubernetes.io/name: payshield
    app.kubernetes.io/component: ws
