apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payshield-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payshield
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payshield-celery-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payshield
      app.kubernetes.io/component: celery-worker
