apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch-resources.yaml
  - patch-replicas.yaml

configMapGenerator:
  - name: payshield-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=*

images:
  - name: payshield/api
    newTag: dev
  - name: payshield/celery-worker
    newTag: dev
