apiVersion: apps/v1
kind: Deployment
metadata:
  name: payshield-api
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payshield-celery-worker
spec:
  replicas: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payshield-api
$patch: delete
